feat: maintenance_window support
mineiros-io/terraform-google-composer pull request #11
Opened 2022-06-10 07:31 UTC by czerasz-mineiros

2022-06-10 09:17 UTC, mariux reviewed
thanks for the added feature.. please add
- the new variable to unit-complete test
- update the documentation new variable
- update the change log and prepare a release by updating version in readme.

thanks a lot..

2022-06-14 09:04 UTC, soerenmartius commented
can we still finish this PR? :)

2022-06-23 10:28 UTC, mariux requested changes
some minor changes and a question about required variables..

2022-06-23 10:28 UTC, mariux commented on CHANGELOG.md
>  [unreleased]: https://github.com/mineiros-io/terraform-google-composer/compare/v0.1.0...HEAD
```suggestion
[unreleased]: https://github.com/mineiros-io/terraform-google-composer/compare/v0.2.0...HEAD
```

2022-06-23 10:28 UTC, mariux commented on README.tfdoc.hcl
> +          description = "(Optional) The configuration settings for Cloud Composer maintenance windows."
```suggestion
          description = "The configuration settings for Cloud Composer maintenance windows."
```

2022-06-23 10:28 UTC, mariux commented on README.tfdoc.hcl
> +              (Required) Start time of the first recurrence of the maintenance window
```suggestion
            type        = string
            required    = true
            description = <<-END
              Start time of the first recurrence of the maintenance window
```

2022-06-23 10:28 UTC, mariux commented on README.tfdoc.hcl
> +              (Required) Maintenance window end time. It is used only to calculate the duration of the maintenance window. The value for end-time must be in the future, relative to 'start_time'.
```suggestion
            type        = string
            required    = true
            description = <<-END
              Maintenance window end time. It is used only to calculate the duration of the maintenance window. The value for end-time must be in the future, relative to 'start_time'.
```

2022-06-23 10:28 UTC, mariux commented on README.tfdoc.hcl
> +              (Required) Maintenance window recurrence. Format is a subset of RFC-5545 (https://tools.ietf.org/html/rfc5545) 'RRULE'. The only allowed values for 'FREQ' field are 'FREQ=DAILY' and 'FR
```suggestion
            type        = string
            required    = true
            description = <<-END
              Maintenance window recurrence. Format is a subset of [RFC-5545](https://tools.ietf.org/html/rfc5545) `RRULE`. The only allowed values for `FREQ` field are `FREQ=DAILY` and `FREQ=WEEKLY;BYDAY=…`. Example values: `FREQ=WEEKLY;BYDAY=TU,WE`, `FREQ=DAILY`.
```

2022-06-23 10:28 UTC, mariux commented on main.tf
> +      for_each = var.maintenance_window != null ? [1] : []
```suggestion
      for_each = var.maintenance_window != null ? [var.maintenance_window] : []
```

2022-06-23 10:28 UTC, mariux commented on main.tf
> +        recurrence = try(var.maintenance_window.recurrence, null)
if those are required, why do we default to null?

```suggestion
        start_time = try(maintenance_window.value.start_time, null)
        end_time   = try(maintenance_window.value.end_time, null)
        recurrence = try(maintenance_window.value.recurrence, null)
```

2022-06-23 16:06 UTC, mariux requested changes
the requested changes are not fully implemented the variables in the the block are not marked required yet.

2022-06-24 11:58 UTC, mariux approved these changes
lgtm

2022-06-24 11:58 UTC, merged